services:
  - type: web
    name: truenumber-backend
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
